remote_theme: pmarsceill/just-the-docs
# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2012-2019 Speech Processing Solutions - Peter Rittau - Customer Support Management. Distributed by an <a href=\"https://github.com/44213/master/LICENSE.txt\">MIT license.</a>"
